---
title: "STOPPD_terminal"
author: "Navona"
date: "January 18, 2018"
output: html_document
---

#This script cleans up the naming of STOPPD scans as they exist in the file system.

```{r setup, include=FALSE}

library('stringi')
library('stringr')
library('plyr')
library('tidyr')
```

```{r import_data}

#import spreadsheet ('ls' of file system)
terminal <- read.csv('../data/stoppd_NiiFolderContents_2018-01-25.csv', header = TRUE)

```

```{r data_cleaning}

#make scan ID character string
terminal$scan_id <- as.character(terminal$scan_id)

#fix scan ID for STOPPD02_MAS_210030_02
#terminal$scan_id[terminal$scan_id == 'STOPPD02_MAS_210030_02'] <- 'STOPPD_MAS_210030_02' #fixed

#make a new column for site component of ID
terminal$site <- str_sub(terminal$scan_id, 8, 10)

#cut out study and site component from ID (first 11 characters)
terminal$scan_id <- substring(terminal$scan_id, 12)

#make a new column for session component of ID
terminal$session <- str_sub(terminal$scan_id, -2)
table(terminal$session)

#cut out session information from ID (last 3 characters)
terminal$scan_id <- stri_sub(terminal$scan_id, 1, -4)

#make a new column that captures alphabetic component of ID ('R')
terminal$contains_R <- grepl('R', terminal$scan_id, fixed=TRUE) #36 participants

#cut out the 'R' in some participant IDs (indicates repeat for controls)
terminal$scan_id <- gsub("[R]", "", terminal$scan_id)

#fix incorrect CAMH scan IDs
#terminal$scan_id[terminal$scan_id == '24S024'] <- "410031"
#terminal$scan_id[terminal$scan_id == '24S025'] <- "420032"
#terminal$scan_id[terminal$scan_id == '24S027'] <- "420039"
#terminal$scan_id[terminal$scan_id == '420008'] <- '410008' #fixed

#make a 'group' column to capture case vs. control information
terminal$group <- stri_sub(terminal$scan_id, 2, 2) #note: 1 or 2 is patient, 6 is control

#change numbers in 'group' column to labels for clarity
terminal$group[terminal$group == 1] <- "patient"
terminal$group[terminal$group == 2] <- "patient"
terminal$group[terminal$group == 6] <- "control"

#make a variable that combines unique ID and session number
terminal$id_session <- paste(terminal$scan_id, '_', terminal$session, sep='')

#write csv
write.csv(terminal, '../generated_csvs/terminal_clean_2018-01-25.csv', row.names=FALSE)

```
