---
title: "STOPPD"
author: "Navona"
date: "January 19, 2018"
output: pdf_document
---

#This script combines information in XNAT, study logs, and randomization information, into a master spreadsheet

```{r setup}
library('stringi')
library('plyr')
library('tidyr')
library('stringr')
```

```{r import_data}

#import spreadsheets 
xnat <- read.csv('../generated_csvs/xnat_clean_2018-01-25.csv') #generated by me
randomization <- read.csv('../data/randomization.csv') #from Judy
log <- read.csv('../data/master_log.csv', fileEncoding="latin1", na.strings=c(""," ","NA"))#from Judy

#transform XNAT df from long to wide format
xnat <- xnat[!names(xnat) %in% c('contains_R', 'id_session')]
xnat <- reshape(xnat, idvar = "MR.ID", timevar = 'session', direction = "wide") 
colnames(xnat) <- c('subject_id', 'first_date_xnat', 'second_date_xnat', 'third_date_xnat', 'acute_date_xnat')

```

```{r merging}

#merge xnat with randomization - will get rid of controls, etc
df <- merge(randomization[c('STUDYID', 'BLINDMED')], xnat, all.x=TRUE, by.x='STUDYID', by.y = 'subject_id') 

#rename randomization column
colnames(df)[colnames(df)=="BLINDMED"] <- "randomization" 

#clean up the 'reason' column in the log file
log$Specify.reason.if.scan.not.completed.1[log$Specify.reason.if.scan.not.completed.1 == "NA" ] <- NA #change all 'N/A' values to proper NA
log$Specify.reason.if.scan.not.completed.1[log$Specify.reason.if.scan.not.completed.1 == "N/A" ] <- NA #change all 'N/A' values to proper NA
log$Specify.reason.if.scan.not.completed.2[log$Specify.reason.if.scan.not.completed.2 == "NA" ] <- NA #change all 'N/A' values to proper NA
log$Specify.reason.if.scan.not.completed.2[log$Specify.reason.if.scan.not.completed.2 == "N/A" ] <- NA #change all 'N/A' values to proper NA
log$Specify.reason.if.scan.not.completed.3[log$Specify.reason.if.scan.not.completed.3 == "NA" ] <- NA #change all 'N/A' values to proper NA
log$Specify.reason.if.scan.not.completed.3[log$Specify.reason.if.scan.not.completed.3 == "N/A" ] <- NA #change all 'N/A' values to proper NA

#combine the 'notes' columns in the log file
log$Comments.1 <- paste(log$Specify.reason.if.scan.not.completed.1, log$Comments.1)
log$Comments.2 <- paste(log$Specify.reason.if.scan.not.completed.2, log$Comments.2)
log$Comments.3 <- paste(log$Specify.reason.if.scan.not.completed.3, log$Comments.3)

#make subset of variables from log we want to merge
log <- log[c(
"STOPPD.clinical.Trial.ID.Imaging.ID", 
"Date.of.randomization...Stop.PD",
"Date.of.consent.to.imaging.study",
"If.not.enrolled.to.imaging.study..specify.reason.", 
"Study.day.of.acute.phase.MRI",
"Scan.completed.Y.N",
"Date.of.MRI..1" , 
"Study.week",
"Scan.completed.Y.N.1", 
"Comments.1",
"Date.of.MRI..2",                                            
"Study.week.1",                                              
"Scan.completed",  
"Comments.2",
"Date.of.MRI..3",                                            
"Study.week.2",                                             
"Scan.completed.1",
"Comments.3")] 

#rename the columns of the variables from log we want to merge
colnames(log) <- c(
  'subject_id', 
  'randomization_date',
  'imaging_consent_date',
  'imaging_nonconsent_reason',
  'acute_date_log',
  'acute_complete_log',
  'first_date_log',
  'first_timepoint_log',
  'first_complete_log',
  'first_notes',
  'second_date_log',
  'second_timepoint_log',
  'second_complete_log',
  'second_notes',
  'third_date_log',
  'third_timepoint_log',
  'third_complete_log',
  'third_notes')

#merge the df and log data
df <- merge(df, log, all.x=TRUE, by.x = 'STUDYID', by.y='subject_id')

#reorder df columns
df <- df[c(
 "STUDYID",              
 "randomization",     
'randomization_date',
'imaging_consent_date',
'imaging_nonconsent_reason',
 "acute_date_log",       
 "acute_complete_log", 
 "acute_date_xnat",   
 "first_date_log",      
 "first_timepoint_log",  
 "first_complete_log", 
 'first_notes', 
 "first_date_xnat",
 "second_date_log",     
 "second_timepoint_log", 
 "second_complete_log", 
 'second_notes',
 "second_date_xnat",
 "third_date_log",      
 "third_timepoint_log",  
 "third_complete_log",
 'third_notes',
 "third_date_xnat")]

#clean up df
df[ df == "N/A" ] <- NA #change all 'N/A' values to proper NA
df[ df == "xx" ] <- NA  #change all 'xx' values to proper NA
df[ df == ""] <- NA #turn all blank values in df into NA

#make sure dates, etc are characters (not factors) by converting all factors to characters
i <- sapply(df, is.factor)
df[i] <- lapply(df[i], as.character)

#clean up the values in the notes columns
df$first_notes[ df$first_notes == "NA NA" ] <- NA #change all 'N/A' values to proper NA
df$first_notes[ df$first_notes == "N/A N/A" ] <- NA #change all 'N/A' values to proper NA
df$first_notes[ df$first_notes == "NA" ] <- NA #change all 'N/A' values to proper NA
df$first_notes[ df$first_notes == "NA N/A" ] <- NA #change all 'N/A' values to proper NA

df$second_notes[ df$second_notes == "NA NA" ] <- NA #change all 'N/A' values to proper NA
df$second_notes[ df$second_notes == "N/A N/A" ] <- NA #change all 'N/A' values to proper NA
df$second_notes[ df$second_notes == "NA" ] <- NA #change all 'N/A' values to proper NA
df$second_notes[ df$second_notes == "NA N/A" ] <- NA #change all 'N/A' values to proper NA

df$third_notes[ df$third_notes == "NA NA" ] <- NA #change all 'N/A' values to proper NA
df$third_notes[ df$third_notes == "N/A N/A" ] <- NA #change all 'N/A' values to proper NA
df$third_notes[ df$third_notes == "NA" ] <- NA #change all 'N/A' values to proper NA
df$third_notes[ df$third_notes == "NA N/A" ] <- NA #change all 'N/A' values to proper NA

#alter incorrect/unclear values as required
df$acute_complete_log <- as.character(df$acute_complete_log)
df$acute_complete_log[df$acute_complete_log == "N" & df$STUDYID == '420043'] <- NA #superflous 'no'

df$first_complete_log[df$first_complete_log == "No" & df$STUDYID == '210045'] <- NA #superflous 'no'
df$first_complete_log[df$first_complete_log == "No" & df$STUDYID == '410016'] <- NA #superflous 'no'
df$first_complete_log[df$first_complete_log == "No" & df$STUDYID == '410026'] <- NA #superflous 'no'
df$first_complete_log[df$first_complete_log == "No" & df$STUDYID == '410033'] <- NA #superflous 'no'
df$first_complete_log[df$first_complete_log == "No" & df$STUDYID == '420010'] <- NA #superflous 'no'
df$first_complete_log[df$first_complete_log == "No" & df$STUDYID == '420012'] <- NA #superflous 'no'
df$first_complete_log[df$first_complete_log == "No" & df$STUDYID == '420025'] <- NA #superflous 'no'
df$first_complete_log[df$first_complete_log == "No" & df$STUDYID == '420028'] <- NA #superflous 'no'
df$first_complete_log[df$first_complete_log == "No" & df$STUDYID == '420041'] <- NA #superflous 'no'

df$second_complete_log[df$second_complete_log == "No" & df$STUDYID == '110030'] <- NA #superflous 'no'
df$second_complete_log[df$second_complete_log == "No" & df$STUDYID == '210024'] <- NA #superflous 'no'
df$second_complete_log[df$second_complete_log == "No" & df$STUDYID == '310070'] <- NA #superflous 'no'

df$third_timepoint_log[df$third_timepoint_log == "what would be RCT Week 36"] <- "RCT Week 36"

df$acute_complete_log[df$acute_complete_log == 'Y'] <- "Yes"

#remove 'day' information from 'acute_date_log' and turn into integer
df$acute_date_log <- sub('\\,.*', '', df$acute_date_log)
df$acute_date_log <- sub('\\,.*', '', df$acute_date_log)
df$acute_date_log <- substr(df$acute_date_log, 11, 12)
df$acute_date_log <- as.numeric(df$acute_date_log)
df$acute_week_log <- df$acute_date_log
df <- subset(df, select = -acute_date_log)

#separate timepoint source and week information in 'first_timepoint_log' variable
df <- cbind(df, as.data.frame(matrix(str_split_fixed(df$first_timepoint_log, " Week ", 2), ncol = 2, byrow = FALSE)))
df <- subset(df, select = -first_timepoint_log)
colnames(df)[colnames(df)=="V1"] <- "first_timepoint_log"
colnames(df)[colnames(df)=="V2"] <- "first_week_log"

#remove accidental extra space in character
df$second_timepoint_log[df$second_timepoint_log == 'Off protocol '] <- 'Off protocol'

#separate timepoint source and week information in 'second_timepoint_log' variable
df <- cbind(df, as.data.frame(matrix(str_split_fixed(df$second_timepoint_log, " Week ", 2), ncol = 2, byrow = FALSE)))
df <- subset(df, select = -second_timepoint_log )
colnames(df)[colnames(df)=="V1"] <- "second_timepoint_log"
colnames(df)[colnames(df)=="V2"] <- "second_week_log"

#recode anything containing 'relapse' in 'second_timepoint_log' variable as simply 'relapse'
df$second_timepoint_log <- as.character(df$second_timepoint_log)
df$second_timepoint_log <- ifelse(grepl('Relapse', df$second_timepoint_log), "Relapse", df$second_timepoint_log)

#recode anything containing 'Protocol' in 'second_timepoint_log' variable as simply 'off protocol'
df$second_timepoint_log <- ifelse(grepl('Protocol', df$second_timepoint_log), "Off protocol", df$second_timepoint_log)

#separate timepoint source and week information in 'third_timepoint_log' variable
df <- cbind(df, as.data.frame(matrix(str_split_fixed(df$third_timepoint_log, " Week ", 2), ncol = 2, byrow = FALSE)))
df <- subset(df, select = -third_timepoint_log )
colnames(df)[colnames(df)=="V1"] <- "third_timepoint_log"
colnames(df)[colnames(df)=="V2"] <- "third_week_log"

#compare dates in df that comes from log vs. XNAT (in new column)
df$first_dateDiff <- round(difftime(df$first_date_log, df$first_date_xnat, units = "days"), 2)
df$second_dateDiff <- round(difftime(df$second_date_log, df$second_date_xnat, units = "days"), 2)
df$third_dateDiff <- round(difftime(df$third_date_log, df$third_date_xnat, units = "days"), 2)

#make sure new variables are characters (not factors), and turn blank values into NA
i <- sapply(df, is.factor)
df[i] <- lapply(df[i], as.character)
df[df == ""] <- NA

#calculate the difference in weeks between scan 2 and scan 1 (i.e., calculate 'second week log' when absent)
df$dateDiff_first_second <- round(difftime(df$second_date_log, df$first_date_log, units = "weeks"), 0)
df$dateDiff_first_second <- as.numeric(df$dateDiff_first_second) #turn variables into integers 
df$first_week_log <- as.numeric(df$first_week_log) #turn variables into integers 
df$second_week_log <- ifelse(is.na(df$second_week_log) & !is.na(df$second_timepoint_log), paste(df$dateDiff_first_second + df$first_week_log, 'est', sep = ' '), df$second_week_log) 

#calculate the difference between 01 and 02 scans, and 02 and 03 scans, and make sure that the greater is always after
#df$firstXsecond <- round(difftime(df$second_date_log, df$first_date_log, units = "weeks"), 0)
#df$secondXthird <- round(difftime(df$third_date_log, df$second_date_log, units = "weeks"), 0) #all later

#reorder df columns
df <- df[c(
"STUDYID",             
"randomization", 
'randomization_date',  
'imaging_consent_date',
'imaging_nonconsent_reason',
"acute_week_log",       
"acute_complete_log",   
#"acute_date_xnat",     
"first_date_log", 
"first_timepoint_log", 
"first_week_log",  
"first_complete_log",
'first_notes',
#"first_date_xnat", 
#"first_dateDiff",
"second_date_log",
"second_timepoint_log", 
"second_week_log",  
"second_complete_log", 
'second_notes',
#"second_date_xnat",  
#"second_dateDiff",
"third_date_log",  
"third_timepoint_log",  
"third_week_log", 
"third_complete_log",   
'third_notes'
#"third_date_xnat"
#"third_dateDiff"
)]      

#remove '_log' component of all variable names, for clarity
names(df) = gsub(pattern = "_log", replacement = "", x = names(df))

#make sure all blanks are NA
df[ df == "" ] <- NA #turn blank space into proper NAs

#write csv
write.csv(df, '../generated_csvs/STOPPD_masterDF_2018-01-25.csv', na = "", row.names=FALSE)

```









