---
title: |
  | <br><br><br><br>STOPPD mean diffusivity analysis
  | (entorhinal cortex only)
output:
  pdf_document:
    latex_engine: xelatex
    toc: yes
    toc_depth: '2'
  html_document:
    latex_engine: xelatex
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r set_up, include = FALSE}

#load libraries
library(tidyverse)
library(lme4)
library(lmerTest)
library(growthmodels)
library(reshape2)
library(ggplot2)
library(stringi)

#bring in subject info
sub_info <- read.csv('../generated_csvs/subject_info.csv')

#bring in sex and age data (from previous spreadsheet)
sexAge <- read.csv('../generated_csvs/STOPPD_errorCases_2018-02-09.csv')

#bring in MD data (from the filesystem)
MD <- read.csv('../data/enigmaDTI-MD_2018-03-08.csv')

```

```{r MD_datacleaning, include = FALSE}

#pull timepoint info from subject ID
MD$timepoint <- str_sub(MD$id, -2, -1)

#remove scans from unwanted timepoints
MD <- MD[!(MD$timepoint == '03'),]
MD <- MD[!(MD$timepoint == '00'),]

#clean up subject ID
MD$id <- substring(MD$id, 12) #remove first 12 chars
MD$id <- str_sub(MD$id, 1, -4) #remove last 3 chars

#remove anyone with an R in their ID - these are repeats
MD <- MD[!grepl("R", MD$id),]

#remove anyone where second digit is 6 - these are controls
MD$control <- str_sub(MD$id, 2, 2)
MD <- MD[!(MD$control == '6'),]

#make df contain only variables we care about
MD <- MD[,c(
  'id',
  'timepoint',
  'EC_MD'
)]

#move from wide to long format
MD_wide <- reshape(MD, idvar = "id", timevar = "timepoint", direction = "wide")

#remove participants who do not have second timepoint data
MD_wide <- na.omit(MD_wide)

#merge subject info
df <- merge(MD_wide, sub_info, by.x = 'id', by.y = 'STUDYID')

#merge sex and age data
df <- merge(df, sexAge[c('STUDYID', 'Sex', 'Age')], by.x = 'id', by.y = 'STUDYID' )

#rename timepoint variable for clarity
colnames(df)[colnames(df)=="second_timepoint"] <- "category" 

#make sure that the ID is numeric
df$id <- as.numeric(df$id)

```

```{r data_munging, include = FALSE}

#turn off scientific notation
options(scipen = 999)

#make difference scores 
df$diffEC_MD <- df$EC_MD.02 - df$EC_MD.01

#turn dateDiff into numeric
df$dateDiff <- as.numeric(df$dateDiff)

#gather and separate df
mdf <- df %>%
  gather(oldcolname, metric_t, ends_with(".01"), ends_with(".02")) %>%
  separate(oldcolname, into = c("metric", "timepoint"), sep = "_") %>%
  mutate(model_days = if_else(str_sub(timepoint, -1, -1)=="1", 1, dateDiff)) 

#make a df with only RCT completers
df_rct <- df[(df$category == "RCT"),]
#df_rct <- df_rct[!(df_rct$id == "210030"),] #take out participant 210030 because of CT score

```

```{r data_review, include = FALSE}

#make sure relationship is linear
plot_linear <- scatter.smooth(x=df_rct$EC_MD.01, y= df_rct$EC_MD.02) 

#check shape
par(mfrow=c(1, 2))
plot_01 <- boxplot(df_rct$EC_MD.01, main = "timepoint 1") 
plot_02 <- boxplot(df_rct$EC_MD.02, main = "timepoint 2") 

#check density, i.e., if close to normality
par(mfrow=c(1, 2))
plot(density(df_rct$EC_MD.01), main = "timepoint 1") 
plot(density(df_rct$EC_MD.02), main = "timepoint 2") 

#check correlation
cor(df_rct$EC_MD.01, df_rct$EC_MD.02) 

```

## RCT only

```{r rct_EC}

#boxplot of difference in MD in EC (y axis) by randomization group (x axis)
plot <- ggplot(df_rct, aes(x= randomization, y = diffEC_MD)) + geom_boxplot() + geom_jitter() + labs(y = 'difference')
plot

#run linear model without covariates
fit_rct <- lm(diffEC_MD ~ randomization + (1|id), data= df_rct)
print(fit_rct)
summary(fit_rct)

#run linear model with covariates of sex and age
fit_rct <- lm(diffEC_MD ~ randomization + Sex + Age + (1|id), data= df_rct)
print(fit_rct)
summary(fit_rct)

```

## RCT & Relapse (with time as factor)

```{r all_EC}

#make a subset of data for just EC
EC <- mdf[(mdf$metric == 'EC'),]

#plot
EC %>%
  ggplot(aes(x=model_days, y=metric_t, colour=randomization)) + 
  geom_point() + 
  geom_line(aes(group=id), alpha = 0.5) + 
  geom_smooth(method="lm", formula=y~poly(x,1)) +
  labs(y = 'EC') + 
  theme_minimal() 

#run mixed linear model, with covariates
fit_all <- lmer(metric_t ~ randomization*model_days + Sex + Age + (1|id), data= EC)
summary(fit_all)

```
