---
title: |
  | <br><br><br><br>STOPPD mean diffusivity analysis
  | left SLF
written: 2018-03-08
edited: 2018-09-09
lastrun: Sys.Date()
output: 
  pdf_document:
    latex_engine: xelatex
    toc: yes
    toc_depth: '2'
---

#This script analyses mean diffusivity in the left superior longitudinal fasciculus.

```{r set_up, include = FALSE}

#load libraries
library(tidyverse)
library(lme4)
library(lmerTest)
library(growthmodels)
library(reshape2)
library(ggplot2)
library(stringi)

#bring in MD data 
MD <- read.csv('../generated_csvs/STOPPD_MDclean.csv') #clean MD dataset created in 06b_STOPPD_MD-EC_2018_03_08.Rmd

#bring in subject info (generated by 03_STOPPD_masterDF.Rmd)
df <- read.csv('../generated_csvs/STOPPD_masterDF_2018-09-06.csv')

```

```{r datacleaning, include = FALSE}

#merge subject info
df <- merge(MD[, c('id', 'dateDiff', 'SLF.L_MD.01', 'SLF.L_MD.02')], df[, c("STUDYID", 'sex', 'age', 'randomization', 'second_timepoint')], by.x = 'id', by.y = 'STUDYID')

#rename timepoint variable for clarity
colnames(df)[colnames(df)=="second_timepoint"] <- "category" 

#turn off scientific notation
options(scipen = 999)

#make difference score
df$diffSLF.L_MD <- df$SLF.L_MD.02 - df$SLF.L_MD.01

#make sure that the ID is numeric
df$id <- as.numeric(df$id)

#make sure dataDiff is numeric, not integer
df$dateDiff <- as.numeric(df$dateDiff)

#restructure data for RCT completers only (N=41)
RCT_MD_SLF <- df[(df$category == "RCT"),]

#restructure data for RCT & Relapse participants (N=74)
RCTRelapse_MD_SLF <- df %>%
  gather(oldcolname, metric_t, ends_with(".01"), ends_with(".02")) %>%
  separate(oldcolname, into = c("metric", "timepoint"), sep = "_") %>%
  mutate(model_days = if_else(str_sub(timepoint, -1, -1)=="1", 1, dateDiff)) 

#write out clean dataframe
write.csv(RCT_MD_SLF, '../generated_data/df_MD_leftSLF.csv', row.names=FALSE)

```

## RCT only; left SLF

```{r RCT_lSLF, warning = FALSE}

#boxplot of difference in MD in left SLF (y axis) by randomization group (x axis)
(plot <- ggplot(RCT_MD_SLF, aes(x = randomization, y = diffSLF.L_MD)) + 
   geom_boxplot(outlier.shape = NA) + geom_jitter() + 
  ggtitle("Mean diffusivity in the left superior longitudinal fasciculus") +
   xlab("randomization condition") +  
   ylab("difference between timepoints"))

#Note: the outlying participant is again 210030; this participant has NOT been excluded from subsequent stats

#run linear model without covariates
fit_rct <- lm(diffSLF.L_MD ~ randomization + (1|id), data= RCT_MD_SLF)
print(fit_rct)
summary(fit_rct)

#run linear model with covariates of sex and age
fit_rct <- lm(diffSLF.L_MD ~ randomization + sex + age + (1|id), data= RCT_MD_SLF)
print(fit_rct)
summary(fit_rct)

```

## RCT & Relapse (with time as factor) - left SLF

```{r RCTRelapse_lSLF, warning = FALSE}

#plot
RCTRelapse_MD_SLF %>%
  ggplot(aes(x=model_days, y=metric_t, colour=randomization)) + 
  geom_point() + 
  geom_line(aes(group=id), alpha = 0.5) + 
  geom_smooth(method="lm", formula=y~poly(x,1)) +
  ggtitle("Mean diffusivity in the left superior longitudinal fasciculus over time") +
  xlab("days between MRIs") +  
  ylab("thickness value") +
  theme_minimal()

#run mixed linear model, with covariates
fit_all <- lmer(metric_t ~ randomization*model_days + sex + age + (1|id), data=RCTRelapse_MD_SLF)
summary(fit_all)

#cleanup
rm(df, fit_all, fit_rct, MD, plot, RCT_MD_SLF, RCTRelapse_MD_SLF)
```



